blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    # View posts by tag
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    # View posts by year, month, day, and slug
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    # View to share a post via email
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    # The comment URL is no longer needed as it's handled in post_detail
    # RSS feed
    path("feed/", LatestPostsFeed(), name="post_feed"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

# Define the sitemaps
sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    # Admin URL
    path("admin/", admin.site.urls),
    # Blog URLs
    path("blog/", include("blog.urls", namespace="blog")),
    # Sitemap URL
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from taggit.managers import TaggableManager


# Post model with a custom manager to retrieve published posts only
class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


# Blog Post model
class Post(models.Model):
    
    tags = TaggableManager()
    
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    objects = models.Manager()  # The default manager.
    published = PublishManager()  # Our custom manager.

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    # Method to get the absolute URL of a post
    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.strftime("%m"),
                self.publish.strftime("%d"),
                self.slug,
            ],
        )

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            slug = slugify(self.title)
            # Ensure slug is unique for the publication date
            unique_slug = slug
            num = 1
            while Post.objects.filter(
                publish__date=self.publish.date(), slug=unique_slug
            ).exists():
                unique_slug = "{}-{}".format(slug, num)
                num += 1
            self.slug = unique_slug
        super().save(*args, **kwargs)


class Comment(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "Comment by {} on {}".format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

# Form to share a post via email
class EmailPostForm(forms.Form):
 name = forms.CharField(max_length=25)
 email = forms.EmailField()
 to = forms.EmailField()
 comments = forms.CharField(required=False,
 widget=forms.Textarea)

# Form to add a comment to a post
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from .models import Post
from django.db.models import Count


# Create your views here.


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        "blog/post/list.html",
        {"page": page, "posts": posts, "tag": tag},
    )


# View function for single post detail
def post_detail(request, year, month, day, post):
    """Display a single post (published) identified by slug & publish date."""

    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == "POST":
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
    .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
    .order_by('-same_tags','-publish')[:4]    

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
            "similar_posts": similar_posts,
        },
    )


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False
    if request.method == "POST":
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd["name"], cd["email"], post.title
            )
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd["name"], cd["comments"]
            )
            send_mail(subject, message, "admin@myblog.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )

blog/templates/blog/base.html
<!-- # blog/templates/blog/base.html -->

{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
 <div id="content">
 {% block content %}
 {% endblock %}
 </div>
 <div id="sidebar">
 <h2>My blog</h2>
 <p>This is my blog. I've written {% total_posts %} posts so far. </p>

 <h3>Latest posts</h3>
 {% show_latest_posts 3 %}

 <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
 </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
 <h1>{{ post.title }}</h1>
 <p class="date">
 Published {{ post.publish }} by {{ post.author }}
 </p>
 <p class="tags">
    Tags:
    {% for tag in post.tags.all %}
      <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
  </p>
 {{ post.body|linebreaks }}
 <p>
 <a href="{% url "blog:post_share" post.id %}">
 Share this post
 </a>
</p>
{% with comments.count as total_comments %}
 <h2>
 {{ total_comments }} comment{{ total_comments|pluralize }}
 </h2>
{% endwith %}
    {% for comment in comments %}
    <div class="comment">
    <p class="date">
    {{ comment.created }} by {{ comment.name }}
    </p>
    {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>No comments yet.</p>
    {% endfor %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">Add comment</button>

    </form>

    {% if similar_posts %}
    <h2>Similar posts</h2>
    
    {% for similar_post in similar_posts %}
      <p>
        <a href="{{ similar_post.get_absolute_url }}">
          {{ similar_post.title }}
        </a>
      </p>
    {% endfor %}
    
    {% endif %}


{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
 <li>
 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
{% empty %}
 <li>No posts available.</li>   
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
  {% endfor %}
 
  {% include "pagination.html" with page=posts %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
 {% if sent %}
 <h1>E-mail successfully sent</h1>
 <p>
 "{{ post.title }}" was successfully sent to {{ cd.to }}.
 </p>
 {% else %}
 <h1>Share "{{ post.title }}" by e-mail</h1>
 <form action="." method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <input type="submit" value="Send e-mail">
 </form>
 {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
 <span class="step-links">
{% if page.has_previous %}
	<a href="?page={{ page.previous_page_number }}">Previous</a>
 {% endif %}
 <span class="current">
 Page {{ page.number }} of {{ page.paginator.num_pages }}.
 </span>
{% if page.has_next %}
	<a href="?page={{ page.next_page_number }}">Next</a>
 {% endif %}
 </span>
</div>